### ISSUE TITLE
Unable to import library

### ISSUE THREAD

**Issue by viswa-swami** [quatanium/foscam-python-lib#15]
After install pyfoscam, I am unable to import the library.

```
>>> from foscam import FoscamCamera
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/foscam/__init__.py", line 1, in <module>
    from foscam import FoscamCamera
ImportError: cannot import name 'FoscamCamera'
```

If I change the code in __init__.py to 

`from foscam.foscam import FoscamCamera
`
Then, it is working fine.  I am able to import and communicate with camera.

Can you please check and update accordingly ?

**Comment by viswa-swami** [comment]
Not sure how, but i tried from a test python script, and that seemed to work.  Sorry about the confusion. Will reopen if i recreate it again.
